### ISSUE TITLE
Adding this to installer dotfiles

### ISSUE THREAD

**Issue by partounian** [roxma/python-support.nvim#8]
I have tried using `nvim +PythonSupportInitPython2 +PythonSupportInitPython3 +qall`, but that does not run the commands/install it. Any suggestions?

**Comment by roxma** [comment]
I'm not sure about the issue.

Do you mean that the commands `:PythonSupportInitPython2`  and `:PythonSupportInitPython3` are not working?

The two commands should print some execution info on neovim's builtin terminal,  which might be useful for debugging.

**Comment by partounian** [comment]
They do work, but not with that command on a script. I am just looking for a way to automatically install the pip modules with my dotfiles script. This might give some useful context: https://github.com/partounian/dotfiles/blob/master/script/functions.sh#L71

**Comment by roxma** [comment]
The command ends before the spwaned process ends. I think this is the reason it fails.

**Comment by roxma** [comment]
I've change the behavior. it should work now.

**Comment by roxma** [comment]
Closing, reopen if it's still not working.

**Comment by partounian** [comment]
Any idea how to skip the prompt in vim? `Press ENTER or type command to continue`
I tried `nvim '+silent PlugInstall' +qall` but no dice :(

**Comment by pschmitt** [comment]
Sorry to necrobump but I still encounter errors when installing non-interactively:

```
$ nvim +PythonSupportInitPython2 +PythonSupportInitPython3 +qall
zsh: abort (core dumped)  nvim +PythonSupportInitPython2 +PythonSupportInitPython3 +qall
$ echo $?
134
```
